# Generated by Django 4.1.6 on 2023-02-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_course_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=128)),
                ('subject', models.CharField(max_length=128)),
                ('message', models.TextField(max_length=1024)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('checked', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
